#############################################################################
# Makefile for building: MACETcpWrapper
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  MACETcpWrapper.pro
# Template: subdirs
# Command: C:\Qt\5.11.2\mingw53_32\bin\qmake.exe -o Makefile MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.11.2\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.11.2\mingw53_32\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.11.2\mingw53_32\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-common \
		sub-Demo_Tcp \
		sub-Demo_MACE \
		sub-Tcp \
		sub-MACETcpWrapper


sub-common-qmake_all:  FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd common\ && $(MAKE) -f Makefile qmake_all
sub-common: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-common-make_first: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-common-all: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-common-clean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-common-distclean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-common-install_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-common-uninstall_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Demo_Tcp-qmake_all:  FORCE
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd Demo_Tcp\ && $(MAKE) -f Makefile qmake_all
sub-Demo_Tcp: FORCE
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Demo_Tcp-make_first: FORCE
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Demo_Tcp-all: FORCE
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Demo_Tcp-clean: FORCE
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Demo_Tcp-distclean: FORCE
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Demo_Tcp-install_subtargets: FORCE
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Demo_Tcp-uninstall_subtargets: FORCE
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Demo_MACE-qmake_all:  FORCE
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd Demo_MACE\ && $(MAKE) -f Makefile qmake_all
sub-Demo_MACE: FORCE
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Demo_MACE-make_first: FORCE
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Demo_MACE-all: FORCE
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Demo_MACE-clean: FORCE
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Demo_MACE-distclean: FORCE
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Demo_MACE-install_subtargets: FORCE
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Demo_MACE-uninstall_subtargets: FORCE
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Tcp-qmake_all:  FORCE
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd Tcp\ && $(MAKE) -f Makefile qmake_all
sub-Tcp: FORCE
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Tcp-make_first: FORCE
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Tcp-all: FORCE
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Tcp-clean: FORCE
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Tcp-distclean: FORCE
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Tcp-install_subtargets: FORCE
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Tcp-uninstall_subtargets: FORCE
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MACETcpWrapper-qmake_all:  FORCE
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd MACETcpWrapper\ && $(MAKE) -f Makefile qmake_all
sub-MACETcpWrapper: FORCE
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MACETcpWrapper-make_first: FORCE
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MACETcpWrapper-all: FORCE
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MACETcpWrapper-clean: FORCE
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MACETcpWrapper-distclean: FORCE
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MACETcpWrapper-install_subtargets: FORCE
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MACETcpWrapper-uninstall_subtargets: FORCE
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: MACETcpWrapper.pro ../../Qt/5.11.2/mingw53_32/mkspecs/win32-g++/qmake.conf ../../Qt/5.11.2/mingw53_32/mkspecs/features/spec_pre.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/qdevice.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/device_config.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/common/sanitize.conf \
		../../Qt/5.11.2/mingw53_32/mkspecs/common/gcc-base.conf \
		../../Qt/5.11.2/mingw53_32/mkspecs/common/g++-base.conf \
		../../Qt/5.11.2/mingw53_32/mkspecs/common/angle.conf \
		../../Qt/5.11.2/mingw53_32/mkspecs/common/windows-vulkan.conf \
		../../Qt/5.11.2/mingw53_32/mkspecs/common/g++-win32.conf \
		../../Qt/5.11.2/mingw53_32/mkspecs/qconfig.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/qt_functions.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/qt_config.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/win32-g++/qmake.conf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/toolchain.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/default_pre.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/win32/default_pre.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/resolve_config.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/default_post.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/qml_debug.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/precompile_header.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/warn_on.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/qmake_use.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/file_copies.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/win32/windows.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/testcase_targets.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/exceptions.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/yacc.prf \
		../../Qt/5.11.2/mingw53_32/mkspecs/features/lex.prf \
		MACETcpWrapper.pro
	$(QMAKE) -o Makefile MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
../../Qt/5.11.2/mingw53_32/mkspecs/features/spec_pre.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/qdevice.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/features/device_config.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/common/sanitize.conf:
../../Qt/5.11.2/mingw53_32/mkspecs/common/gcc-base.conf:
../../Qt/5.11.2/mingw53_32/mkspecs/common/g++-base.conf:
../../Qt/5.11.2/mingw53_32/mkspecs/common/angle.conf:
../../Qt/5.11.2/mingw53_32/mkspecs/common/windows-vulkan.conf:
../../Qt/5.11.2/mingw53_32/mkspecs/common/g++-win32.conf:
../../Qt/5.11.2/mingw53_32/mkspecs/qconfig.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.11.2/mingw53_32/mkspecs/features/qt_functions.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/qt_config.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/win32-g++/qmake.conf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.11.2/mingw53_32/mkspecs/features/exclusive_builds.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/toolchain.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/default_pre.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/win32/default_pre.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/resolve_config.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/default_post.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/qml_debug.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/precompile_header.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/warn_on.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/qmake_use.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/file_copies.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/win32/windows.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/testcase_targets.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/exceptions.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/yacc.prf:
../../Qt/5.11.2/mingw53_32/mkspecs/features/lex.prf:
MACETcpWrapper.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-common-qmake_all sub-Demo_Tcp-qmake_all sub-Demo_MACE-qmake_all sub-Tcp-qmake_all sub-MACETcpWrapper-qmake_all FORCE

make_first: sub-common-make_first sub-Demo_Tcp-make_first sub-Demo_MACE-make_first sub-Tcp-make_first sub-MACETcpWrapper-make_first  FORCE
all: sub-common-all sub-Demo_Tcp-all sub-Demo_MACE-all sub-Tcp-all sub-MACETcpWrapper-all  FORCE
clean: sub-common-clean sub-Demo_Tcp-clean sub-Demo_MACE-clean sub-Tcp-clean sub-MACETcpWrapper-clean  FORCE
distclean: sub-common-distclean sub-Demo_Tcp-distclean sub-Demo_MACE-distclean sub-Tcp-distclean sub-MACETcpWrapper-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-common-install_subtargets sub-Demo_Tcp-install_subtargets sub-Demo_MACE-install_subtargets sub-Tcp-install_subtargets sub-MACETcpWrapper-install_subtargets FORCE
uninstall_subtargets: sub-common-uninstall_subtargets sub-Demo_Tcp-uninstall_subtargets sub-Demo_MACE-uninstall_subtargets sub-Tcp-uninstall_subtargets sub-MACETcpWrapper-uninstall_subtargets FORCE

sub-common-debug:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Demo_Tcp-debug:
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Demo_MACE-debug:
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Tcp-debug:
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MACETcpWrapper-debug:
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-common-debug sub-Demo_Tcp-debug sub-Demo_MACE-debug sub-Tcp-debug sub-MACETcpWrapper-debug

sub-common-release:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Demo_Tcp-release:
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Demo_MACE-release:
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Tcp-release:
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MACETcpWrapper-release:
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-common-release sub-Demo_Tcp-release sub-Demo_MACE-release sub-Tcp-release sub-MACETcpWrapper-release

sub-common-check:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Demo_Tcp-check:
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Demo_MACE-check:
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Tcp-check:
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MACETcpWrapper-check:
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-common-check sub-Demo_Tcp-check sub-Demo_MACE-check sub-Tcp-check sub-MACETcpWrapper-check

sub-common-benchmark:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Demo_Tcp-benchmark:
	@if not exist Demo_Tcp\ mkdir Demo_Tcp\ & if not exist Demo_Tcp\ exit 1
	cd Demo_Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_Tcp\Demo_Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Demo_MACE-benchmark:
	@if not exist Demo_MACE\ mkdir Demo_MACE\ & if not exist Demo_MACE\ exit 1
	cd Demo_MACE\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Demo_MACE\Demo_MACE.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Tcp-benchmark:
	@if not exist Tcp\ mkdir Tcp\ & if not exist Tcp\ exit 1
	cd Tcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\Tcp\Tcp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MACETcpWrapper-benchmark:
	@if not exist MACETcpWrapper\ mkdir MACETcpWrapper\ & if not exist MACETcpWrapper\ exit 1
	cd MACETcpWrapper\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\mace\MACETcpWrapper\MACETcpWrapper\MACETcpWrapper.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-common-benchmark sub-Demo_Tcp-benchmark sub-Demo_MACE-benchmark sub-Tcp-benchmark sub-MACETcpWrapper-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

